spring:
  datasource:
    url: jdbc:mysql://47.99.167.147:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Xsheng@0727
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: 101.200.123.157:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    consumer:
      bootstrap-servers: 101.200.123.157:9092
      group-id: consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: myboot-core

mybatis:
  type-aliases-package: com.study.myboot.bean
  mapper-locations: classpath:mappers/*.xml

server:
  port: 80
  servlet:
    context-path: /myboot/core

eureka:
  instance:
    prefer-ip-address: true   #注册服务的时候使用服务的ip地址
  client:
    service-url:
        defaultZone: http://localhost:8081/myboot/eureka/
