server:
  port: 8081
  servlet:
    context-path: /myboot
eureka:
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8081/myboot/eureka/
    eureka:
      instance:
      hostname: eureka-server  # eureka实例的主机名
spring:
  application:
    name: myboot-eurake
