server:
  port: 8082
  servlet:
    context-path: /myboot/client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/myboot/eureka/

spring:
  application:
    name: myboot-client

#feign:
#  httpclient:
#    enabled: true
